fix(dropdown): remove hover state background color change #34
AlaskaAirlines/auro-combobox pull request #36
Opened 2022-05-27 21:48 UTC by leeejune

# Alaska Airlines Pull Request

Removed hover state background color change.

**Fixes:** #34  (issue, if applicable)

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-05-27 21:54 UTC, MattSidor approved these changes

2022-06-01 16:53 UTC, jason-capsule42 requested changes
We should be making these changes in auro-dropdown but I want to discuss this further @leeejune .

2022-06-01 23:03 UTC, jason-capsule42 approved these changes

2022-06-01 23:04 UTC, merged

2022-06-01 23:06 UTC, blackfalcon commented
:tada: This PR is included in version 1.2.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-combobox/v/1.2.1)
- [GitHub release](https://github.com/AlaskaAirlines/auro-combobox/releases/tag/v1.2.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: