Refactor and fix all custom JS examples so they will work on the doc site
AlaskaAirlines/auro-combobox pull request #70
Opened 2022-08-31 21:29 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #69 

## Summary:

Makes auro-menu a direct dependency and refactors all examples per the new examples.js POC

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-09-01 16:17 UTC, blackfalcon requested changes
This update is only updating documentation. There is no need for a `fix` prefix or release. Please update the commits to use `docs:`

In other repos we have been using `examples.html` as the API Examples page. For consistency please change file from ./demo/api.html to ./demo/examples.html

I would prefer we save ./api.html if we want to have a review page for the api.md file alone.

2022-09-01 16:30 UTC, jason-capsule42 commented
> This update is only updating documentation. There is no need for a `fix` prefix or release. Please update the commits to use `docs:`
> 
> In other repos we have been using `examples.html` as the API Examples page. For consistency please change file from ./demo/api.html to ./demo/examples.html
> 
> I would prefer we save ./api.html if we want to have a review page for the api.md file alone.

We only have that in a couple repos and I have been changing them all to api.html consistently because they reflect the API tab content on the docsite.

2022-09-01 20:28 UTC, blackfalcon requested changes
Please update from `fix` to `docs` and this is good to go.

2022-09-02 05:03 UTC, merged

2022-09-02 05:05 UTC, blackfalcon commented
:tada: This PR is included in version 1.5.3 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-combobox/v/1.5.3)
- [GitHub release](https://github.com/AlaskaAirlines/auro-combobox/releases/tag/v1.5.3)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: