docs(examples): make doc examples load page specific #79
AlaskaAirlines/auro-combobox pull request #80
Opened 2022-09-11 20:26 UTC by jason-capsule42

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #79

## Summary:

Separate all example JS code to be page specific classes.

e.g. API page examples will only run on the API page.
 

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2022-09-13 23:35 UTC, blackfalcon requested changes

2022-09-13 23:35 UTC, blackfalcon commented on demo/index.html
> +    <!-- <script type="module" src="./examples.js"></script> -->
remove commented-out code.

2022-10-18 15:00 UTC, blackfalcon submitted a review, later dismissed

2022-10-18 17:11 UTC, jordanjones243 approved these changes

2022-10-18 17:12 UTC, merged

2022-11-04 16:12 UTC, blackfalcon commented
:tada: This PR is included in version 1.6.4 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-combobox/v/1.6.4)
- [GitHub release](https://github.com/AlaskaAirlines/auro-combobox/releases/tag/v1.6.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: